version: "3.8"

services:
    dietinha_database:
        image: postgres:13
        container_name: dietinha_database
        hostname: dietinha_database
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data

    app:
        container_name: dietinha_backend_app
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.production
        ports:
            - 3001:3001
        restart: always
        depends_on:
            - dietinha_database

volumes:
    database:
