version: "3.8"

services:
    app:
        container_name: dietinha_backend_app
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:${PORT}"
        volumes:
            - type: bind
              source: ./
              target: /app
