version: "3.8"

services:
    dietinha_database:
        image: postgres:13
        container_name: dietinha_database
        hostname: dietinha_database
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        entrypoint: >
            /bin/sh -c "
            cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
            chmod 600 /var/lib/pgadmin/pgpass;
            chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
            /entrypoint.sh
            "
        container_name: pgadmin
        depends_on:
            - dietinha_database
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        #Volumes: location-in-host:location-in-container
        #Absolute path is not necessary
        volumes:
            - ./pgadmin/servers.json:/pgadmin4/servers.json
            - ./pgadmin/pgpass:/pgadmin4/pgpass
            - pgadmin-data:/var/lib/pgadmin
        restart: unless-stopped

    app:
        stdin_open: true
        container_name: dietinha_backend_app
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.development
        ports:
            - "3001:${PORT}"
        restart: always
        volumes:
            - type: bind
              source: ./
              target: /app
        depends_on:
            - dietinha_database

volumes:
    database:
    pgadmin-data:
