version: "3.8"

services:
    dietinha_database:
        image: postgres:13
        container_name: dietinha_database
        restart: always
        env_file:
            - .env
        ports:
            - 6500:5432

    app:
        container_name: dietinha_backend_app
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:${PORT}"
        volumes:
            - type: bind
              source: ./
              target: /app
        depends_on:
            - dietinha_database
