on:
    push:
        branches:
            - main
name: backend-deploy
jobs:
    build:
        runs-on: self-hosted
        timeout-minutes: 20
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create env file
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
                  envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
                  envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
                  envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
                  envkey_URL_PATH_PREFIX: ${{secrets.URL_PATH_PREFIX}}
                  file_name: .env
                  fail_on_empty: true

            - name: Create firebaseAuth JSON
              uses: jsdaniell/create-json@v1.2.2
              with:
                  name: "privateKey.json"
                  json: ${{secrets.FIREBASE_PRIVATE_KEY}}
                  dir: "src/firebase/"

            - name: Run
              run: docker compose -f docker-compose-prod.yml up --build -d
